spring:
  application:
    name: u-center
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.scyking.ucenter.pojo.model #实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config:
      id-type: AUTO #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    banner: false
