server:
  port: 8081

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  security:
    user:
      name: admin
      password: 123456
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/u_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Root_12root
    # 初始化数据库脚本（初始化结束后可删除该配置）
    initialization-mode: always
    sql-script-encoding: utf-8
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql # 重复启动，会导致主键冲突，从而报错
    continue-on-error: false # false ：sql脚本出错终止服务；true ：继续服务

eureka:
  instance:
    prefer-ip-address: false                                                                # 客户端在注册时使用自己的IP而不是主机名，缺省：false
    ip-address: 127.0.0.1                                                                   # 应用实例IP
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}    # 实例ID
    hostname: ${eureka.instance.ip-address}                                                 # 应用实例主机名

  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/