FROM williamyeh/java8
MAINTAINER scyking
VOLUME /root/jar
ENV LANG C.UTF-8
ENV LANGUAGE zh_CN.UTF-8
ENV LC_ALL C.UTF-8
ENV TZ Asia/Shanghai
COPY  u-center-1.0.0.jar u-center.jar
ENTRYPOINT ["nohup","java","-jar","u-center.jar","&"]
EXPOSE 8081