# Mysql 数据源
spring:
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:8066/DB1?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      connectionTimeout: 300
      maxIdleTime: 600
      maxPoolSize: 10

